### PR TITLE
Python tooling

### PR DESCRIPTION
**Pull request by jonlil**
Hi,

This project of yours is just awesome! I'm my-self in the process of trying to integrate with PRODJ but from a rekordbox perspective. See my project [here](https://github.com/jonlil/pioneer-pro-dj-linux)

So I wanted to learn more about parsing with construct and I felt that this project was missing some testing as documentation for how the parses are ment to work (digging source code is time consuming) :-)

So I spent some time to write unittests for the parts I wanted to learn more about and why not contribute with them to upstream.

Feel free to merge and thanks for a lot of good and clean parsing logic.

### CODE REVIEW

**Comment by jonlil** [comment]
cc @flesniak

**Comment by flesniak** [comment]
Sorry, I'm just really busy currently. I will try to look into it as soon as I've got some spare time. Thanks for the pull request, I appreciate that!

**Comment by jonlil** [comment]
> Sorry, I'm just really busy currently. I will try to look into it as soon as I've got some spare time

No worries, but I would like to point out that my pull request doesn't change any logic. It just adds a simple unittest.

If you like I can spend some more time on building a better testing toolbelt

**Comment by flesniak** [comment]
Thanks, finally merged with commit 85839a209d46b03efd41de846f7a475ffb45988a. I'll see if I can add further test cases in the future, as I have many binary blobs floating around for testing.

**Pull request merged**
